### ISSUE TITLE
[Feature Request] Expose Process or pid while running

### ISSUE THREAD

**Issue by leoafarias** [tekartik/process_run.dart#24]
Looking for a way to  have access to the process while is running. I am currently running a long process, and need to kill it in certain situations. Seems that the process that is created by the `run` command is not exposed.

Exposing the `pid` could be enough.

**Comment by alextekartik** [comment]
Since run returns when the process is terminated, there is no way to return the pid with the current API as it is now. The [start](https://api.flutter.dev/flutter/dart-io/Process/start.html io system API is currently the only way to access the running pid (through the Process class).

The current run API is just some helper around it. Maybe you could share the API you have in mind.

**Comment by leoafarias** [comment]
I saw that on the source code. The simples way I see on accomplishing this might be with a callback of some type. `onProcessStart`. That can in turn return the PID or the process object itself.

**Comment by leoafarias** [comment]
Will go ahead and close this, it seems this has been implemented

**Comment by alextekartik** [comment]
Indeed, sorry for not pinging you on this but as you suggested, an optional `onProcess` has been added to `Shell.run`:

```
Future<List<ProcessResult>> run(String script,
      {void Function(Process process)? onProcess})
```
